apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsuprueba-qa
  namespace: nsdevsu-qa
  labels:
    app: devsuprueba-qa 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsuprueba-qa
  template:
    metadata:
      labels:
        app: devsuprueba-qa 
    spec:
      containers:
      - name: devsuprueba-qa 
        image: hansleolml/devsu:latest
        ports:
        - containerPort: 9091
