apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsuprueba-prod
  namespace: nsdevsu-prod
  labels:
    app: devsuprueba-prod 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsuprueba-prod
  template:
    metadata:
      labels:
        app: devsuprueba-prod 
    spec:
      containers:
      - name: devsuprueba-prod 
        image: hansleolml/devsu:latest
        ports:
        - containerPort: 9091